apiVersion: v1
kind: Service
metadata:
  name: smart-rental-service
  labels:
    app: smart-rental
spec:
  type: LoadBalancer
  selector:
    app: smart-rental
  ports:
    - port: 80
      targetPort: 8000